version: '3'

services:
  server1:
    networks:
      - app
      - default
    build: .
    ports:
      - 5000:5000
    environment:
      Options__IsLeader: True
      Kestrel__Endpoints__Http__Url: "http://server1:5000"

  server2:
    networks:
      - app
      - default
    build: .
    ports:
      - 5001:5001
    environment:
      Options__IsLeader: False
      Kestrel__Endpoints__Http__Url: "http://server2:5001"

  server3:
    networks:
      - app
      - default
    build: .
    ports:
      - 5002:5002
    environment:
      Options__IsLeader: False
      Kestrel__Endpoints__Http__Url: "http://server3:5002"

networks:
  app:
    name: app
